### ISSUE TITLE
Where are specifications/requirements for each project kept?

### ISSUE THREAD

**Issue by LizGrauel** [LizGrauel/GCIpm#13]
**Questions to Answer**
- [ ] How are new features planned?
- [ ] How are product requirements documented?
- [ ] Where are design materials (wireframes, comps, mocks) kept?
- [ ] Who has access to these materials?

**Comment by karljgeisler** [comment]
@LizGrauel  Hi Liz,
Often times right now they are driven by customer.  We typically store this info in Box.  Two good upcoming examples are:  B2B/Taylor Communications and The Childrens Place.

Typically its Chad and I who have access.  Here is a sample:
[B2B Taylor Setup.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56494f2d8fd27d1500149b91/125516c66e82c728ace21e0d46cac6b863b682b083e6ad039758e48139046b313916ac217586f76ae5002e58560e4fad405c0e16a8afda7ea6b66d778e0e58e5d7684d68d47f40f2ecdd42e64bef62994597b5bd8946c1ed3d26e4888f493718011a8eed10.pdf)

**Comment by LizGrauel** [comment]
@karljgeisler ok awesome, thank you! Are the details and To-Dos for these documents tracked as GitHub tickets?

**Comment by karljgeisler** [comment]
@LizGrauel Kind of.  We need to do a better job.  Check out ticket 2580.

**Comment by LizGrauel** [comment]
Closing now. @karljgeisler on a go-forward, if you want to create Requirement tickets in the Magneto project and assign them to me I can break them out into tasks
