### ISSUE TITLE
Groom Labels

### ISSUE THREAD

**Issue by LizGrauel** [LizGrauel/GCIpm#2]
**Problem to Solve**
The labels list here: https://github.com/giftcardimpressions/magento/labels is very long. Some labels are applied to few, if any, tickets. 

**Suggested Solution**

- [ ] Audit existing labels:

- What does the label mean?
- Is the label being used?
- Is the label being used correctly?
- Are there opportunities to consolidate existing labels?
- What labels are missing

- [ ] Create a wiki page defining each label and its proper use

**Comment by LizGrauel** [comment]
@karljgeisler can you take a look here and add descriptions of the current labels: https://docs.google.com/spreadsheets/d/1y3LXg_ew3uXSq-8Gb6DpTpo6zmikVNJQX-6abPE6uwg/edit#gid=0

**Comment by karljgeisler** [comment]
Hey Liz - need access ;)

**Comment by LizGrauel** [comment]
@karljgeisler Granted, sorry about that! Is Liz Trimble ok to have access as well?

**Comment by karljgeisler** [comment]
@LizGrauel Ya - so thats the old GCI gmail account that i'm sometimes logged into, (just named for someone no longer here ) :)
I'll typically use my own gmail.

**Comment by karljgeisler** [comment]
@LizGrauel Updated
