### ISSUE TITLE
Define Estimation Measurements

### ISSUE THREAD

**Issue by LizGrauel** [LizGrauel/GCIpm#4]
**Problem to Solve**
Currently there is a lot of ambiguity about the level of time and effort required for each GitHub issue. This is a huge barrier to planning manageable sprints and predicting which work will be done. It also makes it difficult to prioritize and plan the backlog.

**Suggested Solution**
- [x] Define Story Points
- [x] Educate devs and PMs 
- [x] Agree upon the meaning of story points
- How do points correlate to time?
- [x] Determine how story points will be associated with GitHub issues
- Label?
- Title of Ticket?
- Tracked in another tool (Google sheets?)
- [x] Determine what types of issues are assigned Story Points 
- User Stories 
- New Features
- Change Requests
- Bugs
- [x] Determine when Story Points will be assigned
- Weekly before beginning each sprint?
- [x] Determine what will happen to issues which are too large to be accounted for by a Story Point value
- [x] Document Estimation Process in a central location

**Comment by LizGrauel** [comment]
https://github.com/LizGrauel/GCIpm/wiki/Story-Points in progress, to be completed by 8/23 for Karl and Chad to review

**Comment by LizGrauel** [comment]
@karljgeisler please take a look at https://github.com/LizGrauel/GCIpm/wiki/Story-Points and let me know your thoughts

**Comment by karljgeisler** [comment]
@LizGrauel I like this.  It may make sense for us to jump on a hangout some morning to go through this, but I agree with almost all of it.  Just want to talk through the mechanics.

Let me know when works.

**Comment by LizGrauel** [comment]
@karljgeisler I am remote this week so my schedule is more flexible than normal. I can make any of the following work for a call:

Wednesday: 7:30 am EST or 12:30 pm EST
Thursday: 7:30 am EST, 12:30 pm EST or 5:30 pm EST
Friday: 7:30 am EST 
Sunday: any time after noon EST

Let me know if anything here will work for you!

**Comment by karljgeisler** [comment]
Hey Liz,
Let's do Thursday @ 7:30.

Karl
